### ISSUE TITLE
Covarianza e controvarianza nei generics - contradizzione

### ISSUE THREAD

**Issue by danigit** [dotnet/docs.it-it#42]
Nella documentazione c'è la frase:

"La covarianza e la controvarianza sono termini che fanno riferimento alla possibilità di usare un tipo meno derivato (meno specifico) o più derivato (più specifico) di quanto specificato in origine."

e subito dopo c'è:

"Covariance
Permette di usare un tipo più derivato di quello originariamente specificato."

A me mi sembra che la prima sia una contradizione della seconda, o mi sbaglio?

**Comment by CeciAc** [comment]
Salve @danigit, la discussione è ancora in corso e la decisione verrà aggiornata in seguito appena possibile.  
	 
Grazie per il supporto, 
Team di localizzazione Microsoft C&E

**Comment by CeciAc** [comment]
Salve @danigit 
La traduzione attuale ha risolto questo problema.
"La covarianza e la controvarianza sono termini che fanno riferimento alla possibilità di usare un tipo più derivato (più specifico) o un tipo meno derivato (meno specifico) di quanto specificato in origine. "

Grazie per il supporto, 
Team di localizzazione Microsoft C&E
