### ISSUE TITLE
Trovato problema di interoperabilità COM con Windows Pos Ready 2009, a seguito di aggiornamento KB4134651

### ISSUE THREAD

**Issue by damianofasoli** [dotnet/docs.it-it#45]
Un oggetto EXE ActiveX espone una classe COM con eventi (PippoAux.Connector)
ritornata come valore di ritorno di un metodo GetConnector di un'altra classe COM ActiveX del componente (PippoAux.AppConnector)

Durante la chiamata del client per ottenere la classe esce errore di run-time 430
Dim WithEvents pc As PippoAux.Connector

Private Sub Command1_Click()
    Dim pcloc As Object
    Dim pcc As PippoAux.AppConnector
    Set pcc = New PippoAux.AppConnector
    Set pcloc = pcc.Connect() 
    Set pc = pcloc ' HERE ERROR 430
    pc.SayHello
    Set pcc = Nothing
End Sub

Sembra sia necessario rimuovere l'aggiornamento tornando alla versione precedente di oleaut32.dll (8/10/2006)
Così viene ripristinato il funzionamento corretto

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e0a362ee-8336-a95a-9bcb-fe486669dbcc
* Version Independent ID: 9a230b05-ec16-83e9-b6e9-f3942537d76d
* Content: [Interoperabilità COM nelle applicazioni .NET Framework (Visual Basic)](https://docs.microsoft.com/it-it/dotnet/visual-basic/programming-guide/com-interop/com-interoperability-in-net-framework-applications)
* Content Source: [docs/visual-basic/programming-guide/com-interop/com-interoperability-in-net-framework-applications.md](https://github.com/dotnet/docs.it-it/blob/live/docs/visual-basic/programming-guide/com-interop/com-interoperability-in-net-framework-applications.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Salve, @damianofasoli , 

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione. 
Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS. 

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale. 
Il tuo contributo ai nostri articoli è molto apprezzato.  

Cordiali saluti, 
Il team internazionale Microsoft Docs
