### ISSUE TITLE
Bad italian translation for "cross-cutting concerns"

### ISSUE THREAD

**Issue by svituz** [dotnet/docs.it-it#58]
There is a bad italian translation for cross-cutting concerns which is translated as "problemi di montaggio incrociato". The correct translation is "problemi trasversali"

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: f1beb409-3b01-3cf0-f81e-8d4d2397ae6d
* Content: [Confronto tra schema API Gateway e comunicazione diretta da client a microservizio](https://docs.microsoft.com/it-it/dotnet/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs.it-it/blob/live/docs/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hello, @svituz 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @svituz 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
