### ISSUE TITLE
Useful.

### ISSUE THREAD

**Issue by SaverioFrancesco** [dotnet/docs.it-it#61]
well written.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 4c3f3464-63e0-a40f-c645-59fad8a38b9f
* Version Independent ID: 412ed2a6-36f3-382d-1e8c-979eb80c2c0a
* Content: [Uso della funzionalità Async per l'accesso ai file (C#)](https://docs.microsoft.com/it-it/dotnet/csharp/programming-guide/concepts/async/using-async-for-file-access#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/programming-guide/concepts/async/using-async-for-file-access.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @SaverioFrancesco 

I'll close this as *kudos*
