### ISSUE TITLE
can you please update this info for .NET Framework 4.8?

### ISSUE THREAD

**Issue by absinthetized** [dotnet/docs.it-it#64]
as per provided table Win Server 2019 ships with 4.7.2. Does this mean that 4.7.2 will be the last "LTS" of .NET Framework as an OS component, or 4.8 will receive a long term support (around 10 years) too? Will be 4.8 treated as a component of any long term version of your OSes?! Thank you!

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [Versioni e dipendenze di .NET Framework](https://docs.microsoft.com/it-it/dotnet/framework/migration-guide/versions-and-dependencies#feedback)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs.it-it/blob/live/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Hello, @absinthetized 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
