### ISSUE TITLE
Problems when I press Ctrl+F5

### ISSUE THREAD

**Issue by Serjaek** [dotnet/docs.it-it#67]
Exception ... system.io.filenotfoundexception could not load file or assembly 'system.runtime version=4.2.1.0 ... publickeytoken=b03f5f7f11d50a3a ...
This is what i obtain on VS Community 15.9.14 when I try to follow this guide. If I use F# interactive I obtain is: Program.fs(3,1): error FS0010: Unexpected start of structured construct in definition. Expected '=' or other token. Can someone help me?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: fc2e0bab-9cdb-0ab7-aada-e5ffea24eafe
* Version Independent ID: 940a720d-a93f-fad3-5994-e4d80d44ba93
* Content: [Introduzione a F# in Visual Studio](https://docs.microsoft.com/it-it/dotnet/fsharp/get-started/get-started-visual-studio#feedback)
* Content Source: [docs/fsharp/get-started/get-started-visual-studio.md](https://github.com/dotnet/docs.it-it/blob/live/docs/fsharp/get-started/get-started-visual-studio.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @Serjaek
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Serjaek

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
