### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Istorn** [dotnet/docs.it-it#69]
[VIsual Studio 8.2.5 (build5) sistema operativo: Mac. Si presenta praticamente per ogni vista nel progetto l'errore CS2001 (ovvero "Index.g.cshtml.cs" per qualsiasi View) quando in realtà ci sono tutte quante. Nell'esplora risorse non sono segnati i file mancanti e non sono stati eliminati.]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 19118b55-2585-d38f-87b2-0f79cb984c07
* Version Independent ID: be0bc1f4-5d5d-e813-704c-d73c5eeae58c
* Content: [Errore del compilatore CS2001](https://docs.microsoft.com/it-it/dotnet/csharp/misc/cs2001#feedback)
* Content Source: [docs/csharp/misc/cs2001.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/misc/cs2001.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Istorn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Salve, @Istorn 

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione. 
Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS. 

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale. 
Il tuo contributo ai nostri articoli è molto apprezzato.  

Cordiali saluti, 
Il team internazionale Microsoft Docs
