### ISSUE TITLE
Missing diagram image

### ISSUE THREAD

**Issue by ezin82** [dotnet/docs.it-it#72]
It seems that the html to display the image of the diagram is passed by the html encoding.

The image exists, is present at the following URL:

https://docs.microsoft.com/it-it/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/media/index/internal-versus-external-architecture.png

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 1f07c375-8e96-f4ab-e8d6-30c3553ecb85
* Version Independent ID: 421277e8-7085-809b-9e13-1061008470d8
* Content: [Gestione della complessità aziendale in un microservizio con i modelli DDD e CQRS](https://docs.microsoft.com/it-it/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/index.md](https://github.com/dotnet/docs.it-it/blob/live/docs/architecture/microservices/microservice-ddd-cqrs-patterns/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @ezin82
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
This page uses the new image syntax. I’m wondering if this was tested with loc content before releasing? It seems to be working on the en-us content.

**Comment by CeciAc** [comment]
Hello, @ezin82 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
