### ISSUE TITLE
Missing Figures 5.1 and 5-15 in Development workflow for Docker apps

### ISSUE THREAD

**Issue by zullo91** [dotnet/docs.it-it#73]
Figures 5.1 and 5-15 are not displayed correctly. 
Maybe some tags are missing.

URL: 
https://docs.microsoft.com/it-it/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#feedback

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: c8fefbe8-6f9b-209a-3563-2cb51384707c
* Content: [Flusso di lavoro di sviluppo per app Docker](https://docs.microsoft.com/it-it/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#feedback)
* Content Source: [docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs.it-it/blob/live/docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @zullo91
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zullo91 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
