### ISSUE TITLE
Manca un "non"

### ISSUE THREAD

**Issue by carlomilanesi** [dotnet/docs.it-it#75]
Alla prima riga, dovrebbe essere "se non è null", invece di "se è null". Nella versione inglese c'è giustamente "if it isn't null".

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 038ae35e-c5e9-e1a4-a6dd-afe379201245
* Version Independent ID: d73f3d5a-00d4-2e22-c120-8e8d6d101a54
* Content: [?? e? = Operators C# -riferimento](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/operators/null-coalescing-operator#feedback)
* Content Source: [docs/csharp/language-reference/operators/null-coalescing-operator.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/language-reference/operators/null-coalescing-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @carlomilanesi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Ciao @carlomilanesi: 

Grazie per il contributo. 

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati. 

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche. 

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto. 

Grazie per il supporto. 

Team di Microsoft DOCS Global Experience
