### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by carmineelia** [dotnet/docs.it-it#76]
It would seem that
the code 

services.AddDbContext&lt;CatalogContext&gt;(options =&gt;

must be replaced by

services.AddDbContext&lt;DbContext&gt;(options =&gt;

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 376577d9-c559-9d5d-e263-ff9f0fb6ac27
* Version Independent ID: ab3bbb06-6a80-d6d7-8060-9b93ad8b1f3e
* Content: [Creazione di un microservizio CRUD semplice basato sui dati](https://docs.microsoft.com/it-it/dotnet/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice.md](https://github.com/dotnet/docs.it-it/blob/live/docs/architecture/microservices/multi-container-microservice-net-applications/data-driven-crud-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @carmineelia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs #16965](https://github.com/dotnet/docs/issues/16965) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @carmineelia, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/16965. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
