### ISSUE TITLE
Stampa (Printing)

### ISSUE THREAD

**Issue by LuigiZambetti** [dotnet/docs.it-it#77]
Manca la possibilità di poter stampare direttamente la pagina in un formato pre-impostato per la stampa. 
Missing printing function. 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [Convenzioni di codifica C# - Guida per programmatori C#](https://docs.microsoft.com/it-it/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#feedback)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @LuigiZambetti
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Salve, @LuigiZambetti,

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione.  

Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS.  

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale.  

Il tuo contributo ai nostri articoli è molto apprezzato.   

Cordiali saluti,  

Il team internazionale Microsoft Docs
