### ISSUE TITLE
Problema di traduzione del titolo

### ISSUE THREAD

**Issue by KarmaProd** [dotnet/docs.it-it#79]
Il titolo della pagina in italiano è
Prova... Rileva... Finally (istruzione) - Visual Basic
mentre dovrebbe essere
Try... Catch... Finally (istruzione) - Visual Basic

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 870ea49c-ad84-f940-8d27-17c8b25beb97
* Version Independent ID: 285ef531-525a-8703-0f16-73a3c9e497b0
* Content: [Prova... Rileva... Finally (istruzione) - Visual Basic](https://docs.microsoft.com/it-it/dotnet/visual-basic/language-reference/statements/try-catch-finally-statement)
* Content Source: [docs/visual-basic/language-reference/statements/try-catch-finally-statement.md](https://github.com/dotnet/docs.it-it/blob/live/docs/visual-basic/language-reference/statements/try-catch-finally-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @KarmaProd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Ciao @KarmaProd 

Grazie per il contributo.

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati.

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche.

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto.

Grazie per il supporto.

Team di Microsoft DOCS Global Experience

**Comment by KarmaProd** [comment]
> Ciao @KarmaProd
> 
> Grazie per il contributo.
> 
> I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati.
> 
> Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche.
> 
> Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto.
> 
> Grazie per il supporto.
> 
> Team di Microsoft DOCS Global Experience

Mi sembra molto limitante non poter intervenire almeno sul TITOLO (tag html title) della pagina. Non vorrei avessi frainteso la mia segnalazione.
